apiVersion: v1
kind: Service
metadata:
  name: finance-backend-service
spec:
  type: NodePort  # Expose the service externally
  selector:
    app: finance-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000