apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-backend
  template:
    metadata:
      labels:
        app: finance-backend
    spec:
      containers:
      - name: backend
        image: dhananjayakafle/app_segregation_backend:dev
        env:
        - name: DB_USERNAME
          value: finance_user
        - name: DB_PASSWORD
          value: db_user
        - name: DB_HOST
          value: mysql-finance-service
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: finance_db
        ports:
        - containerPort: 8000
