apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-finance
  template:
    metadata:
      labels:
        app: mysql-finance
    spec:
      containers:
      - name: mysql-finance
        image: mysql/mysql-server:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "finance_db"
        - name: MYSQL_USER
          value: "finance_user"
        - name: MYSQL_PASSWORD
          value: "db_user"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-sql
        configMap:
          name: mysql-init-sql