apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-frontend
  template:
    metadata:
      labels:
        app: finance-frontend
    spec:
      containers:
      - name: frontend
        image: dhananjayakafle/app_segregation_frontend:dev
        ports:
        - containerPort: 3000
