apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP  # Use ClusterIP for internal access
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
