name: CI/CD Pipeline

on:
  push:
    branches:
      - stage  # Trigger on push to the master branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push frontend image
        run: |
          cd frontend
          docker build -t dhananjayakafle/app_segregation_frontend:latest .
          docker push dhananjayakafle/app_segregation_frontend:latest

      - name: Build and push backend image
        run: |
          cd backend
          docker build -t dhananjayakafle/app_segregation_backend:stage .
          docker push dhananjayakafle/app_segregation_backend:stage

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS2 }}

      - name: Install kubectl
        run: |
          az aks install-cli

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group TermProject --name termCluster --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl apply -f k3s/mysql-init-sql-configmap.yaml
          kubectl apply -f k3s/database-deployment.yaml
          kubectl apply -f k3s/database-service.yaml
          kubectl apply -f k3s/backend-deployment.yaml
          kubectl apply -f k3s/backend-service.yaml
          kubectl apply -f k3s/frontend-deployment.yaml
          kubectl apply -f k3s/frontend-service.yaml

      - name: Restart deployments to pull new images
        run: |
          kubectl rollout restart deployment/finance-backend
          kubectl rollout restart deployment/finance-frontend
